export const VENDEDORES = [
  'THIAGO MOTA', 'PRISCILA ARAUJO', 'TAIS ARAUJO', 'MARIA JULIA SOARES', 
  'CLAUDINEI CRUZ', 'ALEXANDRE', 'JOSE ADRIANO', 'KEVIN SILVA', 
  'EROS RODRIGUES', 'DANILO ANDRADE', 'ANSELMO CUNHA', 'FERNANDA TAVARES'
];

export const TIPOS_TELHAS = ['SANDUICHE', 'SIMPLES', 'FORRO'];

export const TIPOS_EPS = ['TP40', 'TP25', 'FORRO', '30MM', '50MM', 'PIR30MM', 'PIR50MM'];

export const TIPOS_FRETE = ['CIF', 'FOB'];

export const DEFAULT_METROS_POR_HORA = {
  'TP40': 400, 'TP25': 300, 'FORRO': 100, '30MM': 90, '50MM': 100, 'PIR30MM': 70, 'PIR50MM': 0
};
